### ISSUE TITLE
can't find the Reports folder

### ISSUE THREAD

**Issue by shihigiun** [wireghoul/dotdotpwn#10]
Hi there,

i installed the latest version of dotdotpwn on my windows, and its modules including Net::FTP, TFTP, Time::Hires, Socket, IO::Socket, Getopt::Std, Switch. When I executed dotdotpwn.pl and pressed Ctrl+C to terminate the test, it tells me Report saved: Reports/TEST_URL_05-28-2016_09-13.txt.

Why can't i find the report folder?

Please help, thanks

**Comment by testusername911** [comment]
same issue here. cant find that "Reports" folder... any help?

**Comment by testusername911** [comment]
@shihigiun apparently, this is the solution as the developer emailed me:

> Hi!
> 
> Thanks for using it.
> 
> Apparently it's been a minor bug, you need to create it in the same directory. "Reports", then, run it again and it'll save the report inside that folder ;-)
> 
> Cheers!

**Comment by azamet90** [comment]
> @shihigiun apparently, this is the solution as the developer emailed me:
> 
> > Hi!
> > Thanks for using it.
> > Apparently it's been a minor bug, you need to create it in the same directory. "Reports", then, run it again and it'll save the report inside that folder ;-)
> > Cheers!

where to create that folder for those users like me installed from kali linux repo?

**Comment by wireghoul** [comment]
This issue was resolved years ago. Try asking Kali support/forums.

**Comment by azamet90** [comment]
> This issue was resolved years ago. Try asking Kali support/forums.

if it is so why not fixed years ago or why not put the information pinned here somewhere?

**Comment by Revermb** [comment]
Hi, no documentation has been made and from what i gather this still isn't fixed.
